### ISSUE TITLE
Error building on Linux (fedora 29)

### ISSUE THREAD

**Issue by jamespo** [sasq64/musicplayer#2]
musicplayer/plugins/openmptplugin/OpenMPTPlugin.cpp:12:10: fatal error: coreutils/split.h: No such file or directory
 #include <coreutils/split.h>
          ^~~~~~~~~~~~~~~~~~~

Where is coreutils? 

Previous checkout d7e51de compiles ok

**Comment by david-barbion** [comment]
Same here. No `split.h` under apone/coreutils...
If I remove `#include <coreutils/split.h>` of the mentioned file, it fails elsewhere:
```
/home/davidb/devel/cm/musicplayer/plugins/openmptplugin/OpenMPTPlugin.cpp: In constructor ‘musix::OpenMPTPlayer::OpenMPTPlayer(std::vector<unsigned char>)’:
/home/davidb/devel/cm/musicplayer/plugins/openmptplugin/OpenMPTPlugin.cpp:62:28: error: cannot convert ‘__gnu_cxx::__alloc_traits<std::allocator<std::__cxx11::basic_string<char> >, std::__cxx11::basic_string<char> >::value_type’ {aka ‘std::__cxx11::basic_string<char>’} to ‘const char*’ in assignment
             type_long = p[0];
```
