### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Osmose** [sasq64/musicplayer#3]
Hi! 

Several of the plugins used in musicplayer have license information, but the library itself doesn't seem to have anything specified. I'm using musicplayer in a program I'd like to distribute soon and I wanna make sure I get the licensing right; can we add a `LICENSE` file clarifying how this library is available?

Thank you!

**Comment by sasq64** [comment]
Sorry I haven't answered sooner.
I usually use MIT license for my projects. So don't worry, you can use it
freely :)
I will try to add a LICENSE soon.

**Comment by Osmose** [comment]
Cool, thanks for the clarification!
